name: Compox tests

on:
  push:
      branches: 
      - main
      - staging
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/astral-sh/uv:0.5-python3.12-bookworm-slim
    steps:
      - name: Set up dependencies
        run: |
          apt-get update && apt-get install -y build-essential pkg-config

      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        run: |
          uv python install 3.10 3.11 3.12 3.13
          uv tool install tox

      - name: Run pytest
        run: |
          uvx tox